### ISSUE TITLE
Exchange 2007 schema error with GetUserAvailabilityRequest example - expecting Timezone

### ISSUE THREAD

**Issue by eino-makitalo** [gautamsi/ews-javascript-api#127] opened 2016-11-17 08:24 UTC
The request failed schema validation: The element \'GetUserAvailabilityRequest\' in namespace \'http://schemas.microsoft.com/exchange/services/2006/messages\' has invalid child element \'MailboxDataArray\' in namespace \'http://schemas.microsoft.com/exchange/services/2006/messages\'. List of possible elements expected: \'TimeZone\' in namespace \'http://schemas.microsoft.com/exchange/services/2006/types\'.'

**Comment by eino-makitalo** [comment] 2016-11-17 08:27
In messages.xsd there is
<xs:complexType name="GetUserAvailabilityRequestType">
<xs:complexContent mixed="false">
<xs:extension base="m:BaseRequestType">
<xs:sequence>
<xs:element ref="t:TimeZone"/>
<xs:element type="t:ArrayOfMailboxData" name="MailboxDataArray"/>
<xs:element minOccurs="0" maxOccurs="1" ref="t:FreeBusyViewOptions"/>
<xs:element minOccurs="0" maxOccurs="1" ref="t:SuggestionsViewOptions"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>

**Comment by eino-makitalo** [comment] 2016-11-17 08:33
Ok. It's not implemented yet 
````javascript
       //todo: implement TimeZone and then LegacyAvailabilityTimeZone
       // var legacyTimeZone:LegacyAvailabilityTimeZone = new LegacyAvailabilityTimeZone(writer.Service.TimeZone);

       // legacyTimeZone.WriteToXml(writer, XmlElementNames.TimeZone);
````

**Comment by omardlhz** [comment] 2016-12-31 16:25
Is there a temporal fix for this?

**Comment by gautamsi** [comment] 2017-01-02 16:07
no fix yet. Still working on Time Zone related enhancement

**Comment by guderkar** [comment] 2017-01-19 20:13
Hey, I also have a problem with date. When I send message using this api or outlook web app and then fetching mime content using this api the date field is 1 hour earlier than it should be. But when I send a message using SMTP or MSA and then fetching it it's OK. I don't know if it's because TimeZone is not implemented yet or if there is some problem with the Exchange server.

**Comment by omardlhz** [comment] 2017-01-19 20:20
@guderkar I was looking into this earlier. The problem is that the server will reply with UTC time including your TimeZone's offset. For example, in my case (Server is in Colombia), if I created an event at 12:00AM (or 00:00:00), the API would show it as 5:00AM (5:00:00). This is because Colombia is in the offset -5:00, which means that you have to subtract five hours to the time that the server replies.

**Comment by guderkar** [comment] 2017-01-19 23:10
I get it but, when I send message to the Exchange server using EWS and then fetch it I get: 'Date: Thu, 19 Jan 2017 22:59:11 +0100'. And when I do the same using SMTP/MSA I get: 'Date: Thu, 19 Jan 2017 23:59:11 +0100'. It just does not make any sense.

**Comment by guderkar** [comment] 2017-01-24 03:41
OK just for clarification. The server correctly responds with UTC time when working with DateTimeReceived property (no matter if mail was sent with ews/smtp/msa). When working with MimeContent property the Date field differs as I described above... why?? I have no idea. It's just some server's weird behavior when it's assembling mime content.
However when I change ExchangeService.TimeZoneDefinition.Id to my local timezone (Central Europe Standard Time) the server responds with correct mime content date field in all cases which was my goal.

```javascript
// This would be the correct solution I guess but not implemented yet
var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2007_SP1, ews.TimeZoneInfo.Local);
```

```javascript
// So I hacked it like this
var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2007_SP1);
var tzName = new Date().toLocaleString('en-US', {
    hour12: false,
    hour: '2-digit',
    timeZoneName: 'long'
}).replace(/^\d\d /, '');
exch.TimeZoneDefinition.Id = tzName;

**Comment by gautamsi** [comment] 2017-06-15 22:54
TimeZoneInfo is now implementd, waiting to publish 0.9 build. I am skipping LegacyTimeZone Though, it is from early days and I personally do not expect many customers using Exchange 2007 SP1 Exchange serer, I may be wrong, let me know if this is absolute necessary

**Comment by gautamsi** [comment] 2017-06-16 19:00
I have changed default Exchange Version to Exchange 2013_SP1 which is default in official ews managed api. You can still use 2007_sp1 version when instantiating the `ExchangeService` object

**Comment by gautamsi** [comment] 2017-06-16 22:01
this is deferred until someone has specific need, LegacyTimeZone is only needed by 2007 SP1 which is way old, hopefully no one that old need this service 😞 

Time Zone related enhancements are tracks in #148

**Closed by gautamsi** 2017-06-16 22:01 UTC
Labels: Code Improvement, deferred
