### ISSUE TITLE
Failing the NTLM challenge with a response of 401 unauthorized

### ISSUE THREAD

**Issue by istersin** [gautamsi/ews-javascript-api#67] opened 2016-06-22 15:09 UTC
Hi,

I have a local Exchange 2010 set up with Basic and NTLM auth running on it. I tested your library against the basic auth and all of the requests it issued passed quite nicely. However the problems occur when I use NTLM. As you noted on the Readme, I use the ntlmXHRApi to overtake the XHR request. I then monitor the requests and I can see the NTLM challenges go off. The first two are 401 unauthorized as expected, but so is the third request, even though it is supposed to pass. Also it contains all the correct headers, including the auth header with the ntlm token.
To be sure that It is not a server issue I used the SoapUI tool to issue the same request. I set it up to send an NTLM request, and it does so fine, passing the NTLM challenge. Which means there is an issue with the library. 
I used the same username/password/domain combo in the library and the SoapUI tool, everything matches so the issue is not in the data I am passing. Any ideas on what is going on?

Btw, a great job you are doing here, this library makes a lot of things easier.

**Comment by gautamsi** [comment] 2016-06-22 15:15
unfortunately I do not have my lab environment for next few days. I am moving to a new city and it is in transit. I can do the test and let you know when I have my lab available.

I can do screen sharing session to troubleshoot if it is urgent for you.

**Comment by istersin** [comment] 2016-06-22 15:19
It isn't urgent since I am anyways doing an estimate of how usable this library is. NTLM not working is a deal breaker in a lot of situations so I will try to understand what is going on here. I will let you know if I find out anything.

**Comment by gautamsi** [comment] 2016-06-22 15:26
you can test/debug yourself using nodejs REPL like Mancy or iron-node. or just hand code the request using soap data form Microsoft sample or output from ews-javascript-api debug with `httpntlm ` library.

**Comment by r1bb3t** [comment] 2016-08-30 00:40
any update on this?  would love to know if ntlm is working.

**Comment by gautamsi** [comment] 2016-08-30 08:33
Do you have test server i can test this with?

**Comment by r1bb3t** [comment] 2016-09-03 00:26
i actually have ntlm working for me now.  not sure if i can be of any assistance but if there's any code anyone would like to see, let me know.

**Comment by gautamsi** [comment] 2016-09-03 20:49
how did you get this fixed? #92 reports that instead of 'user@domain.com' using 'username' for username parameter actually works.  Is this how you got that working?

**Comment by r1bb3t** [comment] 2016-09-06 18:55
i'm actually using exactly what you've provided, including 'user@domain.com'.  however, from my experience, a lot of 401's are due to authentication configuration on the server.  for my recent projects, ive been using iisnode which still allows me to do windows authentication configuration via IIS.  so to me, this looks more like a server configuration issue than a code issue.  have you had NTLM working without IIS?

**Comment by gautamsi** [comment] 2016-09-06 19:17
nope Exchange is not installed without IIS to my knowledge, if you have some other service running to proxy this, it could be middleware. 

Exchange authentication with user@domain.com is based on userprincipalname attribute in AD (user logon name on ad user account tab), this is different than email address. they both can be different for a user. if they are using email address will fail.

**Comment by r1bb3t** [comment] 2016-09-06 20:00
yeah, that's what i thought.  if that's the case, then my IIS authentication configuration has ASP.NET Impersonation enabled and Windows Authentication enabled with (obviously) NTLM as the provider.  any other security has to be disabled.  i was receiving 401 errors until i configured that correctly.  i have your provided NTLM auth code working and pulling in calendar events for multiple rooms.

**Comment by gautamsi** [comment] 2016-09-06 20:09
ASP.net impersonation is different than EWS. EWS sets authentication preference and settings using Exchange configuration. All calls to EWS are intercepted by Exchange Filter (DLL) on IIS. If you make any change to Exchange related settings in IIS it will break exchange connectivity.

**Comment by r1bb3t** [comment] 2016-09-06 20:15
ah, i actually have that enabled for a different reason, outside of my EWS needs. so yeah, impersonation may not be necessary in this case.

**Comment by istersin** [comment] 2016-09-08 13:07
@r1bb3t Can you maybe post some code related to [this](https://gist.github.com/gautamsi/28211eda711e3e7dc04c) on how you got it working. I have NTLM on and Basic off, on my Exchange. I am also using impersonation, and basically do everything as describe in the first post. Did you experience the same thing when setting this up yourself, if so how did you solve it?

I am currently creating and sending requests with minor of a soap library, but I really want to try out this library, and this is the last blocking issue I have.

**Comment by r1bb3t** [comment] 2016-09-09 18:00
my app is designed to grab a list of conference rooms from a database, iterate through them and get the propset for each.  here is a simplified version that works with a single room and no database:

```
module.exports = function (callback) {
  // uncomment next line to disable certificate chain test - only for development
  //process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';

  var ews = require("ews-javascript-api");
  var ntlmXHR = require("./ntlmXHRApi");
  var ntlmXHRApi = new ntlmXHR.ntlmXHRApi("username@domain.com","password");
  
  var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2010_SP1), calenderFolderId = new ews.FolderId(ews.WellKnownFolderName.Calendar,new ews.Mailbox('roomEmail@example.com'));
  // next line hijacks the XHR request from ews-javascript-api and use ntlmxhrapi
  exch.XHRApi = ntlmXHRApi;

  exch.Credentials = new ews.ExchangeCredentials("sdfjslkfsdf", "dfijsdlfjsdkl"); //otherwise error out on null credential
  exch.Url = new ews.Uri("https://your.domain.com/ews/exchange.asmx");
  exch.FindAppointments(calenderFolderId,
    new ews.CalendarView(ews.DateTime.Now,
        new ews.DateTime(ews.DateTime.Now.TotalMilliSeconds + ews.TimeSpan.FromHours(200).asMilliseconds()), 1))
    .then(function (params) {
        var propSet = new ews.PropertySet(ews.BasePropertySet.IdOnly);
        propSet.Add(ews.AppointmentSchema.Subject);
        propSet.Add(ews.AppointmentSchema.Organizer);
        propSet.Add(ews.AppointmentSchema.Start);
        propSet.Add(ews.AppointmentSchema.End);
        ews.EwsLogging.DebugLog(params, true, true);
        exch.LoadPropertiesForItems(params.Items, propSet)
            .then(function (data) {
              callback(data);
            }, function (err) {
              console.log(err);
            })
    }, function (err) {
      console.log(err);
    });
};
```

**Comment by istersin** [comment] 2016-09-09 19:38
@r1bb3t Thanks a lot for the response. I think I tried the exact same thing, but I guess I'll give it another shot, I might have missed something.

**Comment by gautamsi** [comment] 2016-09-09 19:49
If you are working on a development Exchange server, you may want to hit me on email if you want a sharing session. I may be able to help you from Exchange setup side, in case that is the root cause.

**Comment by istersin** [comment] 2016-09-09 20:01
Yeah that might be good but I won't have access to it again until Wednesday. What's your timezone, I'll leave you a message on gitter a day early so we can sync.

**Comment by gautamsi** [comment] 2016-09-09 20:02
I am in India but working mostly the UK/US EST time zone

**Comment by istersin** [comment] 2016-09-09 20:12
Great, I'll ping you a day ahead so we can schedule a hangout on Wednesday if that's fine.

**Comment by gautamsi** [comment] 2016-09-09 20:23
sure, ping me on gitter anytime.

**Comment by gautamsi** [comment] 2016-09-14 22:13
I have updated the gist to catch some errors. 401 can not be fixed as it has to do with username and password. sometime there may be a whitespace not necessarily visible when on large screen with ultra HD display. You can spot by adding `console.log(password.length)` to get length and compare if this is exactly what you expected.

**Comment by gautamsi** [comment] 2016-12-18 18:54
I have converted the gist into its own npm package, [`ews-javascript-api-auth`](/gautamsi/ews-javascript-api-auth)

comment if you are still having issues. This needs an unpublished version which I am still working on you can build form master.

**Comment by gautamsi** [comment] 2017-07-01 01:12
reopen if this is still an issue after using latest `ews-javascript-api` and `ews-javascript-api-auth`

**Closed** 2017-07-01 01:12 UTC
